name: Sync To Gitee
on: page_build
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAtkrurdq4mC6zSWk2RWEnwmWhn86crykLS0XMi/TWSGYYqRjKbiZ+
tJpjvjtWo/l9JecfXBTO1qv2bkSoyqvjrGRcYz4N3hGv8lUzZS1uqBD7zq4QzduMKhfAqD
sFCCa4QghC60iKZ6rTj1QattZlIv0ORrZla9RWELuEp2alWCsVBJ/TZGGXUgnHqY9U8rP6
ZJPHiG6910WO/Y/Pirau7qhnxkJ4geH946t/9HE5BL8wD5mdfw+VS1E6Qs31NgulKvqHoi
GSIMvlfHu5DjBlzqhIUngSQK60aOMUdvr3uw4fI56cQLeXGvekQ7Gkd0Imt/BqPcS6G5rE
A9IikvONtsYV6RFJ8hB+ONIYkFW4U7V4qzCmsscuy07khldjs/5rbBhnLzZQx3e85UkLKT
jmA0viFohddtNHn2sRVisDtHbbCQj3IOKpIZOUauCOkgmRy6UrUAXOica+7gLWjOC3KY6d
glPS/iKvKkoMCOmN1otflh9hmagAQdzrozfm165Dr0U3W6DMO1XpQ3i3nrnPreCJ7i17nh
JUjUidIqsTnoM4hdlWM9H4SISs4ZTw3AWXCnvI2F97Pz3DAhPRYewXqkNbh440+Y7jYWNa
+NM1YCNzoshLH+noVcuoWb33spDd4w/MwCUOBbN7kXq20pwQeWBU0/IpQqR1wK1mdRB8e5
sAAAdI1Qh1yNUIdcgAAAAHc3NoLXJzYQAAAgEAtkrurdq4mC6zSWk2RWEnwmWhn86crykL
S0XMi/TWSGYYqRjKbiZ+tJpjvjtWo/l9JecfXBTO1qv2bkSoyqvjrGRcYz4N3hGv8lUzZS
1uqBD7zq4QzduMKhfAqDsFCCa4QghC60iKZ6rTj1QattZlIv0ORrZla9RWELuEp2alWCsV
BJ/TZGGXUgnHqY9U8rP6ZJPHiG6910WO/Y/Pirau7qhnxkJ4geH946t/9HE5BL8wD5mdfw
+VS1E6Qs31NgulKvqHoiGSIMvlfHu5DjBlzqhIUngSQK60aOMUdvr3uw4fI56cQLeXGvek
Q7Gkd0Imt/BqPcS6G5rEA9IikvONtsYV6RFJ8hB+ONIYkFW4U7V4qzCmsscuy07khldjs/
5rbBhnLzZQx3e85UkLKTjmA0viFohddtNHn2sRVisDtHbbCQj3IOKpIZOUauCOkgmRy6Ur
UAXOica+7gLWjOC3KY6dglPS/iKvKkoMCOmN1otflh9hmagAQdzrozfm165Dr0U3W6DMO1
XpQ3i3nrnPreCJ7i17nhJUjUidIqsTnoM4hdlWM9H4SISs4ZTw3AWXCnvI2F97Pz3DAhPR
YewXqkNbh440+Y7jYWNa+NM1YCNzoshLH+noVcuoWb33spDd4w/MwCUOBbN7kXq20pwQeW
BU0/IpQqR1wK1mdRB8e5sAAAADAQABAAACAFRu4pxOCWAbiVlATS3XcUX+Mt1FIpeS6DNG
MhbFIZdJCrUP0Xsxg1B9jiNncprijQ/IPGM3FBKkdbDfRlsRQJPxrEUfUecAxED3K6X6ZB
2eODOjtg7TWNmKRObm506+OGwFTZGS+OBJZFInv3PeW9vX4AvqoZFPOUnowOmUhpMO6V5J
9OyysxcBhqRHyi3cJOb+99V+jZmvEyrouFVkhiPuhppy4UQve5w/LDX5V1KWh1lCaouWmS
zYg6a7pI8S177PaZE0AW4FYtbEq5Mh4ZXVpiHkkXe6M7+9JhZx6dqPEOc7qN3k6y1HdKMS
Hb5LOonJ5juT6iutBItMgk0UWBd+xmPejxxmUohJQfU9Jylv8PjHU4R1PrhuPyXBh0jGms
fwZfxZXvF2fj0e2vxMm03CcZv+NHSBbtdUgT6jr6JMul++cRuIy/Lki050bL7npVDg2hNz
zTfRlzSO+iX0EzAjlnmSo59Qi+qgUjw8pNQkr9nMJzCY09A3BpViyNPudONoNI35FrHOP+
LSGy1CCNGCwRVIolTRgx1Bo7mh993XzZ8D+rH12K82JN4ViUErdVyxZcgomr/PuUCU1kF0
cZhdaXpgUpt3MI/W1dkX1ScHAoNjQugxmV/eC2nJMOLq52eIQUshIJlVuRe/wol/NY4zTN
h2mh4WxLZwhbcE0+OZAAABAQDQHWRksxlwOnT1UpPtdJq4suT8Qiz2NK0zaiHWtHxLGGw6
7P6W0ZPR3hG/ktQOYHnmF5U+UFTSn1+if4F3gGVjoglsiv14vEhP0d2zSb8F/aleIbCxoc
6fQc5X8HchlQxrXLet1eN4VCCsTiQmmiOBFXsRm1PeBE4GKOhTs+HG4eHGqGJdDBHIlkIH
8TWtYXVQbJOR44TnTKokZ8wyY8neBqOO1inSP2SHyX69EzGGy1dmOOtr/2oExLE7wHSaHZ
+TfYLHXcw67xJGwKcvvtZQRq/hqZCMDZUMeCatYeeSJ8AWhPwu4DZRIn2EECQkyKMDGba/
bHcziSyTSHI6yllRAAABAQDjm7tB0ZWh3/b16pfbAebP5QtlmOf6NeSV0Iw5l723ZwWoWa
vKWBF1XF6N6j4ImprARstrwVN/9GIIiHx+tTZ9AyqHH7G70usVjdoUxYMIdBY7xf5mYEad
cTIqT5ehsrcz+/LmQXmJ0BXI13X/WTxXwRkYeu/j/0/YmIKo1pOJ6WGYGmMLkByrgQBaZV
wzCOxixsFRqugnsUofjKOmLq3IpfQv8zb9CGA1F4a58iP5bEp8eCjnQQyLa0u/I+rECIqd
wBse08MagMsp+GxymDGaLsNEYXuIWMDWRkqJofAZr3O2m3/ExIFLxql8yjjYHD71imd4U4
2oJ+MJjpSQRiDtAAABAQDNCCB15/qxM5fbznK9SJcoB4umwOFR+d+0343bmf/Kl6/xYbdG
zW50mnfLXLyJqwh9TwROK4cE7rjzPaOHxS1oRlPg1pDT3zsePon758vLURCAO/MklQjWLJ
A8BSQifnPu2Gb2grNcFJ1e3XwG+uszj2NlvHsPgXSLSc39zXD0ljMVoVvzK53Cb+CHzLHj
uMS3auAzP74j/IIK/ZglLHVVAxDCKI1aTLWpFn7nySsgJDzvCvpBRnLN7Z2i+dZMOL6nGe
cyACcmQ9ipA424lQcZgNUK8IUhbW44QjUVMVWS0LwUYE6vLUCluSlCoTyEmdE1wp/s1ok7
vAXbiXuQTeWnAAAAEDg3MzEzMjA4M0BxcS5jb20BAg==
        with:
          source-repo: "git@github.com:Tricker39/programming-knowledge.git"
          destination-repo: "git@gitee.com:Tricker39/programming-knowledge.git"
